Repository authenticity-house/ft_transcendence, pull requests merged in 2024-05, with the labels that each got.

#190 [Feat] 게임 기록 생성 및 조회 API 구현
  BE/backend/settings.py
  BE/stats/migrations/0002_alter_match_options_rename_player1_id_match_player1_and_more.py
  BE/stats/migrations/0003_match_winner.py
  BE/stats/models.py
  BE/stats/serializers.py
  BE/stats/urls.py
  BE/stats/views.py
  GAME/requirements.txt
Labels: BE, Feat, API

#191 [Feat] 친구 목록, 보낸 요청, 받은 요청 API 연결
  FE/src/components/MyFriendRequestNode.js
  FE/src/components/modal/profile_modal/FriendInfoContent.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/MyFriendContent.js
  FE/src/constants/apiConfig.js
Labels: Feat, UI/UX, FE, API

#193 [Fix] 회원가입 실패 시 로딩 중에서 멈추는 오류 및 회원가입 실패해도 db에 저장되는 오류 해결
  BE/backend/settings.py
  BE/users/oauth.py
  BE/users/views.py
  FE/src/constants/constants.js
  FE/src/pages/register/RegisterPage.js
  FE/src/pages/register/modals/registerFailModal.js
  FE/src/pages/register/registerAPI.js
Labels: BE, FE, Fix

#195 [Feat] 온라인 1대1 게임 세션 시작
  BE/backend/settings.py
  BE/users/urls.py
  BE/users/views.py
  BE/websocket/game_server.py
  BE/websocket/room_consumer.py
  FE/public/css/styles.css
  FE/src/game/Gamewebsocket.js
  FE/src/game/MessageManager.js
  FE/src/pages/online/rooms/roomManager.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js
  FE/src/pages/register/RegisterPage.js
  FE/src/pages/register/modals/loadingModal.js
  FE/src/pages/register/registerAPI.js
  FE/src/utils/getWebsocketUrl.js
  GAME/Makefile
  GAME/game_server/asgi.py
  GAME/game_server/settings.py
  GAME/game_server/urls.py
  GAME/online/__init__.py
  GAME/online/apps.py
  GAME/online/migrations/__init__.py
  GAME/online/services/__init__.py
  GAME/online/services/session.py
  GAME/online/services/session_manager.py
  GAME/online/urls.py
  GAME/online/views.py
  GAME/requirements.txt
  GAME/session/admin.py
  GAME/session/session_manager.py
  GAME/websocket/backend_api.py
  GAME/websocket/consumers.py
  GAME/websocket/online_consumers.py
  GAME/websocket/routing.py
  nginx/nginx.conf
Labels: BE, Feat, FE, API, Game

#194 [Feat] 닉네임, 비밀번호 수정 API 구현
  BE/users/serializers.py
  BE/users/urls.py
  BE/users/views.py
  nginx/nginx.conf
Labels: BE, Feat, API

#196 [Feat] 사용자 게임 통계 모델 및 게임 통계 요약 조회 API 구현
  BE/stats/migrations/0004_userstat.py
  BE/stats/models.py
  BE/stats/serializers.py
  BE/stats/urls.py
  BE/stats/views.py
  BE/users/views.py
  FE/src/pages/register/registerAPI.js
Labels: BE, Feat, API

#202 [Fix] 퐁 유저 프로필 이미지 반영
  BE/backend/settings.py
  BE/users/adapters.py
  BE/users/serializers.py
  BE/users/urls.py
  GAME/game_server/settings.py
  docker-compose.yml
  nginx/nginx.conf
Labels: BE, Setting, Fix

#200 [Fix] 게임 중 score 관련 정보 서버에서 받아오도록 변경
  FE/src/constants/constants.js
  FE/src/game/MessageManager.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js
Labels: Bug, FE

#203 [Feat] 내 정보 / 친구 정보 요약 통계 api 연결
  FE/src/components/modal/profile_modal/FriendInfoContent.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/MyInfoContent.js
  FE/src/constants/apiConfig.js
Labels: Feat, UI/UX, FE, API

#204 [Feat] 유저 게임 통계 모달 데이터 조회 API 구현
  BE/stats/serializers.py
  BE/stats/urls.py
  BE/stats/views.py
  BE/users/views.py
  BE/websocket/game_server.py
Labels: BE, Feat, API

#209 [Feat] 온라인 1대1 게임 구현
  BE/users/urls.py
  BE/users/views.py
  FE/src/components/modal/modalUtils.js
  FE/src/constants/constants.js
  FE/src/game/GamePage.js
  FE/src/game/Gamewebsocket.js
  FE/src/game/MessageManager.js
  FE/src/game/gameEndModal.js
  FE/src/index.js
  FE/src/pages/local/DuelStatsPage.js
  GAME/online/services/session.py
  GAME/online/services/session_manager.py
  GAME/websocket/backend_api.py
  GAME/websocket/online_consumers.py
Labels: Feat, FE, Game

#207 [Feat] 골 들어간 방향으로 초기 공 방향 설정, 헤더 이미지 및 온라인 메인 이미지, 데이터 연결
  FE/public/css/font.css
  FE/src/components/DuelReport.js
  FE/src/components/DuelStatsData.js
  FE/src/components/FetchOnlineMainScreen.js
  FE/src/components/modal/profile_modal/FriendRecordContent.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/MyRecordContent.js
  FE/src/pages/PlayModePage.js
  FE/src/pages/online/OnlineMainScreenPage.js
  GAME/match/ball.py
  GAME/match/match_manager.py
Labels: Feat, UI/UX, FE, API, Game

#211 [Feat] 로컬 매치 기록 전송 API 구현 및 게임서버 반영
  BE/stats/models.py
  BE/stats/serializers.py
  BE/stats/tests.py
  BE/stats/time_utils.py
  BE/stats/urls.py
  BE/stats/views.py
  BE/users/views.py
  GAME/websocket/backend_api.py
  GAME/websocket/consumers.py
Labels: BE, Feat, API, Game

#213 [Feat] 프로필 사진 수정 API 구현
  BE/backend/settings.py
  BE/requirements.txt
  BE/users/migrations/0007_uploadedimage.py
  BE/users/models.py
  BE/users/serializers.py
  BE/users/urls.py
  BE/users/views.py
Labels: BE, Feat, API

#215 [Feat] 모달 - 통계 API 연결
  FE/public/css/styles.css
  FE/src/components/DuelGraphStats.js
  FE/src/components/ModalGraphStats.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/StatsContent.js
  FE/src/constants/apiConfig.js
Labels: UI/UX, FE, API

#217 [Feat] 온라인 토너먼트 구현
  BE/users/urls.py
  BE/users/views.py
  FE/src/game/GamePage.js
  FE/src/game/MessageManager.js
  FE/src/game/gameEndModal.js
  FE/src/pages/local/TournamentPage.js
  FE/src/pages/local/TournamentResultPage.js
  GAME/match/match_manager.py
  GAME/online/services/session.py
  GAME/online/services/session_manager.py
  GAME/online/urls.py
  GAME/online/views.py
  GAME/session/session_manager.py
  GAME/websocket/backend_api.py
  GAME/websocket/consumers.py
  GAME/websocket/online_consumers.py
  GAME/websocket/routing.py
Labels: Feat, FE, Game

#216 [Feat] Elo 레이팅 적용
  BE/backend/asgi.py
  BE/rooms/services/room.py
  BE/stats/elo_rating.py
  BE/stats/serializers.py
  BE/stats/views.py
  docker-compose.yml
Labels: BE, Feat, API, Fix

#223 [Feat] 랜덤 매치메이킹 추가
  GAME/session/session_manager.py
Labels: Feat, Game

#226 [Feat] 게임 방법 모달 추가 및 내용 추가
  FE/public/css/styles.css
  FE/public/image/in-game-screenshot.png
  FE/src/components/HelpButton.js
  FE/src/components/modal/helpModal.js
  FE/src/game/MessageManager.js
  FE/src/index.js
  FE/src/pages/test.js
Labels: Feat, UI/UX, FE

#218 [Chore] 닉네임 길이에 따른 폰트 조절 및 UI 1차 개선
  FE/public/css/styles.css
  FE/src/components/DuelBasicStats.js
  FE/src/components/DuelSpecialStats.js
  FE/src/components/UserNode.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/MyInfoContent.js
  FE/src/game/GamePage.js
  FE/src/pages/local/DuelStatsPage.js
Labels: UI/UX, FE, Chore

#227 [Feat] 헤더 버튼들 게임중에는 클릭 안되게 설정
  FE/src/components/ProfileButton.js
  FE/src/components/modal/modalUtils.js
  FE/src/index.js
Labels: UI/UX, FE

#234 [Fix] 로컬 토너먼트 경기결과 페이지 - 유저 이미지 넣기
  FE/public/css/styles.css
  FE/public/image/player.png
  FE/src/components/DuelReport.js
Labels: UI/UX, FE, Fix

#233 [Fix] 문자열 길이에 따른 폰트 크기 조절 2차
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/src/components/DuelBasicStats.js
  FE/src/components/MyFriendRequestNode.js
  FE/src/components/TournamentBracket.js
  FE/src/components/modal/profile_modal/StatsContent.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomUserBox.js
Labels: Feat, UI/UX, FE

#237 [Feat] 온라인 토너먼트 다음 버튼 없애기
  FE/src/game/MessageManager.js
  FE/src/pages/local/DuelStatsPage.js
  FE/src/pages/local/TournamentPage.js
Labels: UI/UX, FE

#241 [Feat] 모달 - 통계 공격성향 UI 개선
  FE/public/css/styles.css
  FE/src/components/ModalGraphStats.js
  FE/src/components/modal/profile_modal/StatsContent.js
Labels: Feat, UI/UX, FE

#240 [Feat] 관전자 시각화
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/MyInfoContent.js
  FE/src/game/GamePage.js
  FE/src/pages/online/rooms/roomManager.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js
Labels: Feat, UI/UX, FE

#244 [Feat] 파워 업 기능 추가
  FE/src/components/modal/helpModal.js
  FE/src/game/Gamewebsocket.js
  FE/src/game/MessageManager.js
  GAME/match/ball.py
  GAME/match/match_manager.py
  GAME/match/paddle.py
  GAME/match/player.py
  GAME/online/services/session.py
Labels: BE, Feat, UI/UX, FE, Fix

#239 [Feat] 닉네임 중복검사, 비밀번호 세션 유지 및 정보 수정 API 연결
  BE/rooms/services/room.py
  BE/rooms/services/room_user.py
  BE/users/serializers.py
  BE/users/views.py
  BE/websocket/room_consumer.py
  FE/public/css/styles.css
  FE/src/components/TextInputBox.js
  FE/src/components/modal/profile_modal/MyInfoContent.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/components/modal/profile_modal/updateProfile/updateNicknameListener.js
  FE/src/components/modal/profile_modal/updateProfile/updatePasswordListener.js
  FE/src/components/modal/profile_modal/updateProfile/updateProfileAPI.js
  FE/src/components/modal/profile_modal/updateProfile/updateProfileUtils.js
  FE/src/components/modal/profile_modal/updateProfile/uploadImageListener.js
  FE/src/constants/apiConfig.js
  FE/src/game/GamewebsocketManager.js
  FE/src/pages/online/rooms/roomManager.js
  FE/src/pages/register/RegisterPage.js
  FE/src/pages/register/registerValidCheck.js
Labels: BE, Feat, FE, API

#246 [Hotfix] 방 대기실에서 모달 창 열린 상태에서 게임 시작 시 모달 창 열린 상태인 문제
  FE/src/index.js
Labels: FE, Hotfix

#235 [Deploy] https/wss 적용
  BE/backend/settings.py
  BE/requirements.txt
  BE/users/adapters.py
  BE/users/serializers.py
  BE/users/urls.py
  FE/public/index.html
  FE/src/constants/apiConfig.js
  FE/src/constants/constants.js
  FE/src/utils/getWebsocketUrl.js
  GAME/game_server/settings.py
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: Deploy

#247 [Chore] 필요없는 console.log 삭제
  FE/src/components/FetchOnlineMainScreen.js
  FE/src/components/modal/profile_modal/FriendInfoContent.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/UserSearchContent.js
  FE/src/game/GamePage.js
  FE/src/game/Gamewebsocket.js
  FE/src/game/MessageManager.js
  FE/src/pages/LoginPage.js
  FE/src/pages/online/rooms/roomManager.js
Labels: UI/UX, FE, Chore
