Repository authenticity-house/ft_transcendence, pull requests merged in 2024-03, with the labels that each got.

#4 [Feat] BE 개발환경 설정
  .gitignore
  BE/.pylintrc
  BE/Makefile
  BE/backend/__init__.py
  BE/backend/asgi.py
  BE/backend/settings.py
  BE/backend/urls.py
  BE/backend/wsgi.py
  BE/manage.py
  BE/requirements.txt
  GAME/.pylintrc
  GAME/Makefile
  GAME/game_server/__init__.py
  GAME/game_server/asgi.py
  GAME/game_server/settings.py
  GAME/game_server/urls.py
  GAME/game_server/wsgi.py
  GAME/manage.py
  GAME/requirements.txt
Labels: BE, Setting

#7 [Feat] BE 타입 검사 추가
  BE/Makefile
  BE/backend/settings.py
  BE/requirements.txt
  GAME/Makefile
  GAME/game_server/settings.py
  GAME/requirements.txt
Labels: BE, Setting

#11 Feat: FE 디렉토리 구조 설정 및 예제 파일 생성
  FE/public/index.html
  FE/src/App.js
  FE/src/components/header.js
  FE/src/index.js
  FE/src/pages/Mainpage.js
Labels: FE, Setting

#13 [Feat] css 파일 추가, 기본폰터 설정, 로고 svg 저장 및 접속 시 로고 애니메이션 출력
  .gitignore
  FE/.eslintrc.js
  FE/public/css/reset.css
  FE/public/css/styles.css
  FE/public/index.html
  FE/public/logo.svg
  FE/src/App.js
  FE/src/index.js
Labels: Feat, UI/UX, FE

#15 [Feat] color, font css 제작, 로그인 view 제작(프로토타입), 사이즈 모두 rem으로 변경
  FE/public/css/color.css
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/public/index.html
  FE/src/components/header.js
  FE/src/index.js
  FE/src/pages/Mainpage.js
Labels: Feat, UI/UX, FE

#18 [Feat] index.html에서 view 부분 파일로 분리, history API 구현, SPA 화면 이동 구현, 게임페이지 분리 및 PONG 프로토타입 삽입
  FE/.eslintrc.js
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/index.js
  FE/src/pages/GamePage.js
  FE/src/pages/GuestPage.js
  FE/src/pages/LoginPage.js
  FE/src/pages/Mainpage.js
Labels: UI/UX, FE

#22 [Feat] 간단한 PONG 게임 로직 및 웹소켓 통신 구현
  GAME/.pylintrc
  GAME/Makefile
  GAME/game_server/asgi.py
  GAME/game_server/settings.py
  GAME/game_server/urls.py
  GAME/match/__init__.py
  GAME/match/apps.py
  GAME/match/ball.py
  GAME/match/constants.py
  GAME/match/match_manager.py
  GAME/match/migrations/__init__.py
  GAME/match/models.py
  GAME/match/paddle.py
  GAME/match/player.py
  GAME/match/urls.py
  GAME/match/views.py
  GAME/requirements.txt
  GAME/websocket/__init__.py
  GAME/websocket/apps.py
  GAME/websocket/consumers.py
  GAME/websocket/migrations/__init__.py
  GAME/websocket/routing.py
Labels: Feat, Game

#26 [Feat] 게임 매치 패들 움직임 업데이트 로직 수정
  .gitignore
  GAME/match/match_manager.py
  GAME/websocket/consumers.py
Labels: Feat, Chore, Game

#27 [Feat] 게임 매치 통계 데이터 1차 수집
  BE/backend/settings.py
  GAME/game_server/settings.py
  GAME/match/attack_stat.py
  GAME/match/ball.py
  GAME/match/match_manager.py
  GAME/match/paddle.py
  GAME/match/player.py
  GAME/websocket/consumers.py
Labels: Feat, Refactor, Game

#28 [Feat] 게임 서버-클라이언트 로컬 1대1 웹소켓 규약 적용
  GAME/websocket/consumers.py
Labels: Feat, Game

#38 [Feat] 게임 웹소켓 연결 및 통신
  FE/src/components/TextInputBox.js
  FE/src/pages/GamePage.js
  GAME/match/ball.py
  GAME/match/match_manager.py
Labels: Feat, UI/UX, FE

#42 [Feat] UI / DuelStatsPage(1대1 결과 페이지) 구현
  FE/public/css/styles.css
  FE/src/components/BoldTitle.js
  FE/src/index.js
  FE/src/pages/DuelStatsPage.js
  FE/src/pages/LoginPage.js
  FE/src/pages/RegisterNicknamePage.js
  FE/src/pages/RegisterPage.js
Labels: Feat, UI/UX, FE

#44 [Fix] 공이 벽을 뚫고 무한 반사하는 문제 해결
  GAME/Makefile
  GAME/match/ball.py
  GAME/match/match_manager.py
Labels: Chore, Fix, Game

#46 [Feat] 게임 설정, 세부 설정 UI 제작
  FE/public/css/styles.css
  FE/public/index.html
  FE/src/components/ActivateButtons.js
  FE/src/components/HorizontalButton.js
  FE/src/components/VerticalButton.js
  FE/src/index.js
  FE/src/pages/GamePage.js
  FE/src/pages/GameSettingDetailed.js
  FE/src/pages/GameSettingPage.js
  FE/src/pages/MatchModePage.js
Labels: Feat, UI/UX, FE

#49 [Fix] 게임 서버에서 받아온 정보로 게임 render하도록 변경
  FE/src/pages/GamePage.js
Labels: UI/UX, Fix, Game

#50 [Feat] 게임 파라미터 약간 수정 및 게임 종료 시 통계 반영 및 출력
  FE/src/pages/DuelStatsPage.js
  FE/src/pages/GamePage.js
  GAME/match/ball.py
  GAME/match/match_manager.py
Labels: UI/UX, FE

#53 [Feat] 토너먼트 대진표 UI
  FE/.eslintrc.js
  FE/public/css/styles.css
  FE/src/components/TournamentBracket.js
  FE/src/index.js
  FE/src/pages/MatchModePage.js
  FE/src/pages/TournamentPage.js
Labels: Feat, UI/UX, FE

#56 [Feat] CCW 알고리즘으로 패들 충돌 판별
  GAME/match/coor_util.py
  GAME/match/paddle.py
  GAME/websocket/consumers.py
Labels: Feat, Refactor, Fix, Game

#61 [Feat] 로컬 게임 나가기 구현
  FE/src/pages/GamePage.js
  GAME/match/match_manager.py
  GAME/websocket/consumers.py
Labels: Feat, Fix, Game

#63 [Feat] 게임 종료 후 패들 움직이기 추가
  FE/src/pages/GamePage.js
  GAME/match/match_manager.py
Labels: Feat, FE, Game

#64 [Fix] 게임 세부 설정 초기화되지 않는 오류 해결
  FE/src/pages/GameSettingDetailed.js
  FE/src/pages/GameSettingPage.js
Labels: FE, Fix

#66 [Refactor] 매치 매니저 리팩토링
  GAME/match/ball.py
  GAME/match/match_manager.py
  GAME/match/paddle.py
  GAME/websocket/consumers.py
Labels: Refactor, Game

#67 [Feat] 게임 페이지 플레이어 닉네임 출력, 득점 시 애니메이션 효과 추가
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/src/pages/GamePage.js
Labels: Feat, UI/UX, FE

#69 [Feat] 게임결과 득점 추이 그래프 구현
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/src/components/GraphScore.js
  FE/src/index.js
  FE/src/pages/DuelStatsPage.js
Labels: Feat, UI/UX, FE

#70 [Feat] 토너먼트 게임 설정 페이지 UI 제작 및 설정 초기화 오류 해결
  FE/public/css/styles.css
  FE/public/index.html
  FE/src/components/ActivateButtons.js
  FE/src/components/InputNickname.js
  FE/src/index.js
  FE/src/pages/GameSettingDetailed.js
  FE/src/pages/GameSettingPage.js
  FE/src/pages/GameSettingTournament.js
  FE/src/pages/MatchModePage.js
Labels: Feat, FE, Fix

#71 [Feat] 게임 세션 매니저 초기 구현
  GAME/Makefile
  GAME/session/__init__.py
  GAME/session/admin.py
  GAME/session/apps.py
  GAME/session/migrations/__init__.py
  GAME/session/models.py
  GAME/session/session_manager.py
  GAME/session/tests.py
  GAME/session/views.py
  GAME/websocket/consumers.py
Labels: Feat, Game

#75 [Feat] 게임 설정 페이지 이동시 정보 저장 및 전달
  FE/src/components/InputNickname.js
  FE/src/pages/GameSettingDetailed.js
  FE/src/pages/GameSettingTournament.js
Labels: Feat, FE

#76 [Refactor] 토너먼트 페이지 리팩토링
  FE/public/css/styles.css
  FE/src/components/TournamentBracket.js
  FE/src/pages/LoginPage.js
  FE/src/pages/TournamentPage.js
Labels: FE, Refactor

#79 [Refactor] GamePage에서 Websocket 로직 분리
  FE/src/Gamewebsocket.js
  FE/src/pages/GamePage.js
Labels: FE, Refactor

#84 [Feat] 대진표를 반영하여 토너먼트 진행
  GAME/match/match_manager.py
  GAME/match/paddle.py
  GAME/session/bracket.py
  GAME/session/session_manager.py
Labels: Feat, Game

#82 [Feat] 토너먼트 경기 결과 요약 페이지 UI 제작 (50%)
  FE/public/css/styles.css
  FE/public/image/duel-detail-button.svg
  FE/src/components/DuelReport.js
  FE/src/index.js
  FE/src/pages/LoginPage.js
  FE/src/pages/TournamentResultPage.js
Labels: Feat, UI/UX, FE

#87 [Refactor] 게임 결과 통계 페이지(DuelStatsPage) 리팩토링
  FE/public/css/styles.css
  FE/src/components/DuelBasicStats.js
  FE/src/components/DuelGraphStats.js
  FE/src/components/DuelSpecialStats.js
  FE/src/components/DuelStatsData.js
  FE/src/components/GraphScore.js
  FE/src/components/header.js
  FE/src/pages/DuelStatsPage.js
  FE/src/pages/LoginPage.js
Labels: FE, Refactor

#88 [Hotfix] 로컬 1vs1 게임이 작동되지 않는 문제 해결
  FE/src/pages/GameSettingPage.js
  GAME/match/ball.py
  GAME/session/session_manager.py
  GAME/websocket/consumers.py
Labels: Hotfix, Game

#91 [Feat] 토너먼트 웹소켓 연결 및 게임 흐름 구현
  FE/src/Gamewebsocket.js
  FE/src/pages/DuelStatsPage.js
  FE/src/pages/GamePage.js
  FE/src/pages/GameSettingPage.js
  FE/src/pages/GameSettingTournament.js
  FE/src/pages/TournamentPage.js
  FE/src/pages/TournamentResultPage.js
  GAME/session/bracket.py
Labels: Feat, FE, Game

#92 [Feat] 토너먼트 대진표 페이지 - 데이터 받아서 대진표 띄우기
  FE/src/components/TournamentBracket.js
  FE/src/pages/TournamentPage.js
Labels: UI/UX, FE

#94 [Hotfix] 1vs1 경기 후 게임이 끝나지 않는 오류 해결 및 게임 중 나가기 확인 모달 추가
  FE/public/css/styles.css
  FE/src/pages/DuelStatsPage.js
  FE/src/pages/GamePage.js
Labels: Feat, FE, Hotfix

#96 [Hotfix] 토너먼트 모드 2번째 판부터 Ready가 보이지 않는 오류 수정
  FE/src/Gamewebsocket.js
Labels: FE, Hotfix

#97 [Setting] Docker 세팅
  .gitignore
  BE/Dockerfile
  BE/backend/asgi.py
  BE/backend/settings.py
  BE/requirements.txt
  BE/websocket/__init__.py
  BE/websocket/apps.py
  BE/websocket/migrations/__init__.py
  BE/websocket/room_consumer.py
  BE/websocket/routing.py
  FE/public/favicon.ico
  FE/src/Gamewebsocket.js
  FE/src/index.js
  GAME/Dockerfile
  GAME/game_server/settings.py
  Makefile
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
  nginx/run.sh
Labels: Setting

#98 [Hotfix] 게임 종료 판단 오류 및 공 속도 수정
  GAME/session/bracket.py
  GAME/session/session_manager.py
Labels: Hotfix, Game

#100 [Fix] 게임 나가기 모달창이 켜져있는 상태에서 게임이 종료되면 화면 block상태가 유지되는 오류
  FE/src/Gamewebsocket.js
  FE/src/components/ActivateButtons.js
  FE/src/components/modal/exitModal.js
  FE/src/components/modal/modalUtiils.js
  FE/src/pages/GamePage.js
Labels: FE, Fix

#99 [Feat] 토너먼트 경기 결과 요약 페이지 데이터 띄우기
  FE/public/css/styles.css
  FE/src/components/DuelGraphStats.js
  FE/src/components/DuelReport.js
  FE/src/pages/LoginPage.js
  FE/src/pages/TournamentResultPage.js
Labels: UI/UX, FE

#102 [Setting] 백엔드 서버 Django PostgreSQL 연동
  .gitignore
  BE/Makefile
  BE/backend/settings.py
  BE/requirements.txt
  GAME/game_server/settings.py
  GAME/requirements.txt
  docker-compose.yml
Labels: BE, Setting

#106 [Feat] 토너먼트 대진표 페이지 - 우승자 UI 띄우기
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/src/components/TournamentBracket.js
  FE/src/pages/TournamentPage.js
Labels: Feat, UI/UX, FE

#107 [Feat] 스크롤바 추가, 새로 고침 시 홈페이지로 링크 변경, history 로직 약간 수정 등
  FE/public/css/styles.css
  FE/src/index.js
  FE/src/pages/MatchModePage.js
  FE/src/pages/PlayModePage.js
  FE/src/pages/RegisterNicknamePage.js
  FE/src/pages/RegisterPage.js
  FE/src/pages/TournamentPage.js
Labels: Feat, UI/UX, FE, Chore

#109 [Refactor] 프론트 websocket 관련 부분 리팩토링
  FE/src/Gamewebsocket.js
  FE/src/index.js
  FE/src/pages/DuelStatsPage.js
  FE/src/pages/GamePage.js
  FE/src/pages/GameSettingPage.js
  FE/src/pages/GameSettingTournament.js
  FE/src/pages/TournamentPage.js
  FE/src/pages/TournamentResultPage.js
  FE/src/websocket/Gamewebsocket.js
  FE/src/websocket/MessageManager.js
  FE/src/websocket/constWebsocket.js
  FE/src/websocket/messages.js
Labels: FE, Refactor, Game

#110 [Feat] 온라인 메인 화면 UI 제작
  FE/public/css/styles.css
  FE/public/image/match-record.svg
  FE/public/image/my-friend.svg
  FE/public/image/refresh.png
  FE/public/image/search.svg
  FE/public/image/statistics.svg
  FE/src/components/ProfileButton.js
  FE/src/components/ProfileWindow.js
  FE/src/components/RoomListWindow.js
  FE/src/index.js
  FE/src/pages/OnlineMainScreenPage.js
  FE/src/pages/PlayModePage.js
Labels: Feat, UI/UX, FE

#112 [Feat] history 이동 시 열려있는 gamewebsocket 체크 후 열려있으면 닫고 이동
  FE/src/index.js
  FE/src/pages/GameSettingPage.js
  FE/src/pages/GameSettingTournament.js
  FE/src/websocket/GamewebsocketManager.js
Labels: Feat, FE

#114 [Feat] 온라인 메인화면 - Mock data (profileData)만들어서 UI 띄우기
  FE/public/css/styles.css
  FE/public/image/default-profile.png
  FE/src/components/ProfileButton.js
  FE/src/components/ProfileWindow.js
  FE/src/pages/OnlineMainScreenPage.js
Labels: Feat, UI/UX, FE
