Repository authenticity-house/ft_transcendence, pull requests merged in 2024-04, with the labels that each got.

#115 [Feat] 프로필 모달 UI 제작 + 자잘한 기능들
  FE/public/css/styles.css
  FE/public/image/close.svg
  FE/public/index.html
  FE/src/components/ProfileButton.js
  FE/src/components/modal/profileModal.js
  FE/src/index.js
  FE/src/pages/OnlineMainScreenPage.js
Labels: Feat, UI/UX, FE

#116 [Feat] 로그인, 회원가입, 게임 설정 UI 변경
  FE/public/css/color.css
  FE/public/css/styles.css
  FE/public/image/left_pong.svg
  FE/public/image/right_pong.svg
  FE/src/components/BoldTitle.js
  FE/src/components/InputNickname.js
  FE/src/components/TextInputBox.js
  FE/src/components/pongImage.js
  FE/src/index.js
  FE/src/pages/GameSettingPage.js
  FE/src/pages/GameSettingTournament.js
  FE/src/pages/LoginPage.js
  FE/src/pages/OnlineMainScreenPage.js
  FE/src/pages/RegisterNicknamePage.js
  FE/src/pages/RegisterPage.js
Labels: Feat, FE, Chore

#117 [Feat] 온라인 - 방 대기실 UI 제작
  FE/public/css/color.css
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/public/image/block.svg
  FE/src/components/ButtonExtraLarge.js
  FE/src/components/WaitingRoomInfo.js
  FE/src/components/WaitingRoomUserBox.js
  FE/src/index.js
  FE/src/pages/LoginPage.js
  FE/src/pages/OnlineMainScreenPage.js
  FE/src/pages/WaitingRoomPage.js
Labels: Feat, UI/UX, FE

#119 [Feat] 유저 모델 생성 및 로그인/로그아웃 API 구현
  BE/.pylintrc
  BE/Makefile
  BE/backend/settings.py
  BE/backend/urls.py
  BE/requirements.txt
  BE/stats/__init__.py
  BE/stats/admin.py
  BE/stats/apps.py
  BE/stats/migrations/0001_initial.py
  BE/stats/migrations/__init__.py
  BE/stats/models.py
  BE/stats/tests.py
  BE/stats/views.py
  BE/users/__init__.py
  BE/users/adapters.py
  BE/users/admin.py
  BE/users/apps.py
  BE/users/migrations/0001_initial.py
  BE/users/migrations/0002_alter_user_nickname.py
  BE/users/migrations/0003_alter_user_profile_url.py
  BE/users/migrations/__init__.py
  BE/users/models.py
  BE/users/serializers.py
  BE/users/tests.py
  BE/users/urls.py
  BE/users/views.py
  BE/websocket/room_consumer.py
  Makefile
Labels: BE, API, Chore

#125 [Feat] 모달 Navbar UI 구현, 이벤트 핸들러 등록, 헤더 버튼 클릭 시 해당 탭 모달 오픈
  FE/public/css/color.css
  FE/public/css/styles.css
  FE/public/image/logout.svg
  FE/public/image/my-info.svg
  FE/src/components/ProfileButton.js
  FE/src/components/modal/profileModal.js
  FE/src/index.js
Labels: Feat, UI/UX, FE

#126 [Setting] Nginx와 백엔드 서버 연결
  docker-compose.yml
  nginx/nginx.conf
Labels: Deploy, Setting

#128 [Feat] 내 정보, 내 기록 탭 view UI 제작
  FE/public/css/styles.css
  FE/public/image/edit.svg
  FE/src/components/ProfileButton.js
  FE/src/components/modal/profile_modal/MyInfoContent.js
  FE/src/components/modal/profile_modal/MyRecordContent.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/index.js
  FE/src/pages/TournamentResultPage.js
Labels: Feat, UI/UX, FE

#131 [Feat] 모달 UI 제작(유저 검색 탭, 내 친구 탭)
  FE/public/css/styles.css
  FE/public/image/check-square.svg
  FE/public/image/x-square.svg
  FE/src/components/MyFriendRequestNode.js
  FE/src/components/UserNode.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/MyFriendContent.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/components/modal/profile_modal/UserSearchContent.js
Labels: Feat, UI/UX, FE

#133 [Fix] 그래프 canvas 반응형에 맞게 px 처리하기
  FE/public/css/styles.css
  FE/src/components/DuelGraphStats.js
Labels: UI/UX, FE, Fix

#135 [Feat] 회원가입 이메일 인증 구현
  BE/backend/mail_backends.py
  BE/backend/settings.py
  BE/users/adapters.py
  BE/users/models.py
  BE/users/urls.py
  BE/users/views.py
Labels: BE, API

#136 [Feat] 프론트 로그인/회원가입 연결
  FE/public/css/styles.css
  FE/src/components/ButtonMedium.js
  FE/src/components/TextInputBox.js
  FE/src/components/modal/exitModal.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/components/modal/registerFailModal.js
  FE/src/components/modal/registerLoadingModal.js
  FE/src/components/modal/registerModal.js
  FE/src/index.js
  FE/src/pages/LoginPage.js
  FE/src/pages/RegisterPage.js
  FE/src/pages/online/OnlineGameSettingTournament.js
  FE/src/pages/test.js
  FE/src/utils/areAllFieldsFilled.js
  FE/src/utils/formDataToJson.js
  nginx/nginx.conf
Labels: Feat, FE, API

#139 [Fix] 게임 설정 초기화 안되는 오류 해결
  FE/src/pages/GameSettingDetailed.js
  FE/src/pages/online/OnlineGameSettingDetailed.js
  FE/src/pages/online/OnlineGameSettingTournament.js
Labels: Bug, FE

#140 [Feat] 모달 통계 UI 제작
  FE/public/css/font.css
  FE/public/css/styles.css
  FE/src/components/ModalGraphStats.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/components/modal/profile_modal/StatsContent.js
Labels: Feat, UI/UX, FE

#143 [Setting] nginx.conf 파일에 CORS 에러 해결을 위한 헤더 추가
  BE/users/adapters.py
  nginx/nginx.conf
Labels: Deploy, Setting, Chore, Fix

#141 [Feat] 회원가입에 필요한 필드 중복 검사 API 구현
  BE/users/urls.py
  BE/users/views.py
Labels: BE, Feat, API

#145 [Feat] 로그인 실패 에러문구 표시 및 프론트 api 관련 리팩토링
  FE/public/css/styles.css
  FE/src/components/modal/modalUtiils.js
  FE/src/components/modal/modalUtils.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/constants/apiConfig.js
  FE/src/index.js
  FE/src/pages/LoginPage.js
  FE/src/pages/register/RegisterPage.js
  FE/src/pages/register/registerFailModal.js
  FE/src/pages/register/registerLoadingModal.js
  FE/src/pages/register/registerModal.js
  FE/src/utils/getCookie.js
  FE/src/websocket/MessageManager.js
Labels: FE, API, Chore

#148 [Feat] 방 만들기 API 호출
  BE/rooms/room.py
  BE/rooms/room_manager.py
  BE/rooms/serializers.py
  FE/src/constants/apiConfig.js
  FE/src/pages/online/OnlineGameSettingDetailed.js
  FE/src/pages/online/OnlineGameSettingPage.js
  FE/src/pages/online/OnlineGameSettingTournament.js
  FE/src/pages/online/createRoomAPI.js
Labels: Feat, FE, API

#150 [Feat] 온라인 메인 화면 - 방 조회 API로 UI 업데이트
  FE/src/components/FetchOnlineMainScreen.js
  FE/src/components/ProfileWindow.js
  FE/src/components/RoomListWindow.js
  FE/src/pages/OnlineMainScreenPage.js
Labels: UI/UX, FE, API

#152 [Feat] 회원가입 시 필드 유효성 체크 및 에러관리
  FE/src/components/modal/modalUtils.js
  FE/src/constants/apiConfig.js
  FE/src/pages/register/DuplicateChecker.js
  FE/src/pages/register/RegisterPage.js
  FE/src/pages/register/modals/registerDupModal.js
  FE/src/pages/register/modals/registerFailModal.js
  FE/src/pages/register/modals/registerLoadingModal.js
  FE/src/pages/register/modals/registerModal.js
  FE/src/pages/register/registerAPI.js
  FE/src/pages/register/registerValidCheck.js
Labels: Feat, FE, API

#155 [Bug] canvas 중복 문제 해결
  FE/public/css/styles.css
  FE/src/components/DuelGraphStats.js
  FE/src/components/DuelReport.js
  FE/src/constants/apiConfig.js
  FE/src/pages/DuelStatsPage.js
  FE/src/pages/TournamentResultPage.js
Labels: Bug, FE, Fix

#151 [Feat] 유저 검색 및 특정 유저 프로필 조회 API 구현
  BE/rooms/room_manager.py
  BE/users/serializers.py
  BE/users/urls.py
  BE/users/views.py
Labels: BE, Feat, API

#158 [Feat] 로그인 상태 확인 API 구현
  BE/users/urls.py
  BE/users/views.py
Labels: BE, Feat, API

#160 [Feat] OAuth를 이용한 회원가입 및 로그인
  BE/backend/settings.py
  BE/requirements.txt
  BE/users/oauth.py
  BE/users/urls.py
  BE/users/views.py
  FE/src/constants/constants.js
  FE/src/pages/LoginPage.js
  FE/src/pages/register/registerValidCheck.js
  FE/src/websocket/MessageManager.js
Labels: BE, Feat, FE, API

#162 [Feat] 로그인 상태 관리
  FE/public/css/styles.css
  FE/public/image/question-mark.png
  FE/src/components/ButtonLarge.js
  FE/src/components/ProfileButton.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/constants/apiConfig.js
  FE/src/pages/LoginPage.js
  FE/src/pages/MatchModePage.js
  FE/src/pages/PlayModePage.js
Labels: UI/UX, FE, API

#159 [Feat] 게임 방 참가 기능 구현
  BE/Makefile
  BE/backend/asgi.py
  BE/backend/settings.py
  BE/rooms/admin.py
  BE/rooms/models.py
  BE/rooms/serializers.py
  BE/rooms/services/__init__.py
  BE/rooms/services/exceptions.py
  BE/rooms/services/room.py
  BE/rooms/services/room_manager.py
  BE/rooms/services/room_user.py
  BE/rooms/tests.py
  BE/rooms/urls.py
  BE/rooms/views.py
  BE/websocket/default_consumer.py
  BE/websocket/room_consumer.py
  BE/websocket/routing.py
  FE/src/constants/apiConfig.js
  FE/src/index.js
  FE/src/pages/WaitingRoomPage.js
  FE/src/pages/online/createRoomAPI.js
  FE/src/pages/online/gameSetting/OnlineGameSettingDetailed.js
  FE/src/pages/online/gameSetting/OnlineGameSettingPage.js
  FE/src/pages/online/gameSetting/OnlineGameSettingTournament.js
  FE/src/pages/online/rooms/createRoomAPI.js
  FE/src/pages/online/rooms/joinRoomAPI.js
  FE/src/pages/online/rooms/roomManager.js
  FE/src/utils/getWebsocketUrl.js
  FE/src/websocket/Gamewebsocket.js
  nginx/nginx.conf
Labels: BE, Feat, API

#169 [Feat] 방에 있는 유저 정보 전달
  BE/rooms/services/room.py
  BE/rooms/services/room_manager.py
  BE/rooms/services/room_user.py
  BE/websocket/room_consumer.py
  FE/src/components/FetchOnlineMainScreen.js
  FE/src/index.js
  FE/src/pages/local/DuelStatsPage.js
  FE/src/pages/local/TournamentPage.js
  FE/src/pages/local/TournamentResultPage.js
  FE/src/pages/local/gameSetting/GameSettingDetailed.js
  FE/src/pages/local/gameSetting/GameSettingPage.js
  FE/src/pages/local/gameSetting/GameSettingTournament.js
  FE/src/pages/online/OnlineMainScreenPage.js
  FE/src/pages/online/rooms/joinRoomAPI.js
  FE/src/pages/online/rooms/roomManager.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomInfo.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomUserBox.js
Labels: BE, Feat

#165 [Fix] 전반적인 이미지 크기 수정
  FE/public/css/styles.css
  FE/src/components/FetchOnlineMainScreen.js
  FE/src/components/ProfileButton.js
  FE/src/components/modal/profile_modal/MyInfoContent.js
  FE/src/pages/online/OnlineMainScreenPage.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomUserBox.js
Labels: UI/UX, FE, Fix

#167 [Feat] Local 토너먼트 플레이어 닉네임 입력 검사
  FE/public/css/styles.css
  FE/src/components/InputNickname.js
  FE/src/pages/local/gameSetting/GameSettingTournament.js
Labels: Feat, UI/UX, FE

#172 [Feat] 방 기능 추가(상태 변경, 방 정보 수정, 방 자동 삭제)
  BE/rooms/services/room.py
  BE/rooms/services/room_manager.py
  BE/rooms/services/room_user.py
  BE/websocket/room_consumer.py
Labels: BE, Feat

#174 [Feat] 방 정보 수정, read_state 변경, 방 종료 API 연결
  FE/public/css/styles.css
  FE/src/components/gameSettingDetailed/GameSettingDetailedComponent.js
  FE/src/components/gameSettingDetailed/gameSettingHTML.js
  FE/src/components/gameSettingDetailed/gameSettingUtils.js
  FE/src/components/modal/modalUtils.js
  FE/src/index.js
  FE/src/pages/local/gameSetting/GameSettingDetailed.js
  FE/src/pages/local/gameSetting/GameSettingTournament.js
  FE/src/pages/online/gameSetting/OnlineGameSettingDetailed.js
  FE/src/pages/online/rooms/ModifyGameSetting.js
  FE/src/pages/online/rooms/roomEndModal.js
  FE/src/pages/online/rooms/roomManager.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js
Labels: Feat, FE, API

#180 [Refactor] 게임 페이지 리팩토링 및 방 대기실 오류 수정
  FE/src/components/FetchOnlineMainScreen.js
  FE/src/game/GamePage.js
  FE/src/game/Gamemessages.js
  FE/src/game/Gamewebsocket.js
  FE/src/game/GamewebsocketManager.js
  FE/src/game/MessageManager.js
  FE/src/game/gamePageUtils.js
  FE/src/index.js
  FE/src/pages/GamePage.js
  FE/src/pages/LoginPage.js
  FE/src/pages/MatchModePage.js
  FE/src/pages/PlayModePage.js
  FE/src/pages/local/DuelStatsPage.js
  FE/src/pages/local/TournamentResultPage.js
  FE/src/pages/local/gameSetting/GameSettingPage.js
  FE/src/pages/local/gameSetting/GameSettingTournament.js
  FE/src/pages/online/OnlineMainScreenPage.js
  FE/src/pages/online/gameSetting/OnlineGameSettingPage.js
  FE/src/pages/online/rooms/joinRoomAPI.js
  FE/src/pages/online/rooms/roomManager.js
  FE/src/pages/online/rooms/roomModal.js
  FE/src/pages/online/rooms/waitingRoom/ModifyGameSetting.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js
  FE/src/websocket/GamewebsocketManager.js
  FE/src/websocket/messages.js
Labels: FE, Refactor, Fix

#176 [Chore] 반응형 레이아웃 삭제
  FE/public/css/styles.css
Labels: UI/UX, FE, Chore

#182 [Feat] 친구 요청 관련 API 구현
  BE/users/migrations/0004_user_friends_alter_user_profile_url.py
  BE/users/migrations/0005_friendship_alter_user_friends.py
  BE/users/migrations/0005_remove_friendship_user1_remove_friendship_user2_and_more.py
  BE/users/migrations/0006_merge_20240408_1552.py
  BE/users/models.py
  BE/users/urls.py
  BE/users/views.py
  nginx/nginx.conf
Labels: BE, Feat, API

#183 [Hotfix] migration 실행 파일 추가
  BE/users/migrations/0006_alter_friendship_from_user_alter_friendship_to_user.py
Labels: Hotfix

#181 [Feat] History 관리, 로그인 상태 관리
  FE/public/css/styles.css
  FE/public/index.html
  FE/src/game/GamePage.js
  FE/src/game/MessageManager.js
  FE/src/index.js
  FE/src/pages/LoginPage.js
  FE/src/pages/PlayModePage.js
  FE/src/pages/local/DuelStatsPage.js
  FE/src/pages/local/TournamentResultPage.js
  FE/src/pages/local/gameSetting/GameSettingDetailed.js
  FE/src/pages/local/gameSetting/GameSettingPage.js
  FE/src/pages/local/gameSetting/GameSettingTournament.js
  FE/src/pages/online/OnlineMainScreenPage.js
  FE/src/pages/online/gameSetting/OnlineGameSettingDetailed.js
  FE/src/pages/online/gameSetting/OnlineGameSettingPage.js
  FE/src/pages/online/gameSetting/OnlineGameSettingTournament.js
  FE/src/pages/online/rooms/waitingRoom/WaitingRoomPage.js
  FE/src/utils/browserInfo.js
Labels: Feat, FE, API

#184 [Feat] 유저 노드 이벤트 추가, 친구 모달 구현 및 모달 전환 구현
  .gitignore
  FE/public/css/styles.css
  FE/src/components/MyFriendRequestNode.js
  FE/src/components/UserNode.js
  FE/src/components/modal/profile_modal/FriendInfoContent.js
  FE/src/components/modal/profile_modal/GetContent.js
  FE/src/components/modal/profile_modal/MyFriendContent.js
  FE/src/components/modal/profile_modal/MyInfoContent.js
  FE/src/components/modal/profile_modal/ProfileModal.js
  FE/src/components/modal/profile_modal/UserSearchContent.js
  FE/src/constants/apiConfig.js
  FE/src/pages/LoginPage.js
  FE/src/pages/local/TournamentResultPage.js
  FE/src/pages/register/DuplicateChecker.js
Labels: Feat, UI/UX, FE, API

#186 [Hotfix] 친구 요청 전송 시 friend_pk를 int로 보냈을 경우, 중복 요청 예외 처리
  BE/users/views.py
Labels: BE, Feat, API, Hotfix
